package com.BossAi.bossAi.service.director;

import lombok.*;

import java.util.List;
import java.util.UUID;

/**
 * Visual profile of an asset — gives GPT "eyes".
 *
 * Instead of treating assets as "just another VIDEO/IMAGE file",
 * AssetProfile describes WHAT is in the asset, HOW it looks,
 * and WHAT ROLE it suggests in the edit.
 *
 * Generated by AssetAnalyzer based on:
 *   - metadata (type, duration, prompt/description)
 *   - GPT Vision (if available)
 *   - user context (orderIndex, file name)
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AssetProfile {

    /** Asset ID — 1:1 mapping with Asset.id */
    private UUID assetId;

    /** Index in the user's asset order (from orderIndex) */
    private int index;

    /** Asset type: VIDEO, IMAGE */
    private String assetType;

    /**
     * Visual description of the asset's content.
     * E.g. "Logo animation with blue gradient background"
     * or "Close-up of a person talking to camera, indoor setting"
     */
    private String visualDescription;

    /**
     * Suggested editing role.
     * Values: intro, hook, content, b-roll, product-shot, testimonial,
     *           transition, outro, cta, background
     */
    private String suggestedRole;

    /**
     * Mood/vibe of the asset.
     * E.g. "energetic", "calm", "dramatic", "professional", "playful"
     */
    private String mood;

    /**
     * Visual complexity (0.0-1.0).
     * Low = static, simple. High = dynamic, full of detail.
     * Affects effect choice: simple → ken_burns, complex → cut/minimal.
     */
    private double visualComplexity;

    /**
     * Tags describing the content — used to match against the narration.
     * E.g. ["logo", "brand", "animation"] or ["person", "talking", "indoor"]
     */
    @Builder.Default
    private List<String> tags = List.of();

    /**
     * Duration in seconds (VIDEO only, null for IMAGE).
     */
    private Integer durationSeconds;

    /**
     * Whether the asset is suitable for looping (loop-friendly ending)?
     * True if the end transitions smoothly to the beginning.
     */
    private boolean loopable;

    /**
     * Dominant colors (hex). Optional.
     * May affect the color_grade in EditDna.
     */
    @Builder.Default
    private List<String> dominantColors = List.of();

    /**
     * Whether the asset is suitable as a background (blur behind primary).
     * True for: b-roll, background, scenery, ambient footage, lifestyle.
     * False for: testimonial, product-shot, cta, logo.
     */
    @Builder.Default
    private boolean canBeBackground = false;

    /**
     * Whether the asset is suitable as an overlay (on top of primary).
     * True for: cta, logo, product-shot, button, outro.
     * False for: b-roll, testimonial, content.
     */
    @Builder.Default
    private boolean canBeOverlay = false;

    /**
     * Visual weight — how strongly the asset "demands" the foreground (0.0-1.0).
     * High = wants to be primary (person talking, product reveal).
     * Low = fits as a background (b-roll, ambient).
     */
    @Builder.Default
    private double visualWeight = 0.5;
}
