package com.BossAi.bossAi.service.director;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.util.List;

/**
 * Parsed user instruction at the single-scene level.
 *
 * SceneDirective describes WHAT should appear in a given scene:
 *   - Which layers (background, primary, overlay)
 *   - Where to get the assets (user-provided vs generated)
 *   - How to compose them (fullscreen, overlay, picture-in-picture)
 *   - When this scene should occur
 *
 * Generated by UserIntentParser (GPT parses the user's prompt).
 * Fed into ScriptStep, EdlGeneratorService, CutEngine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class SceneDirective {

    @JsonProperty("scene_index")
    private int sceneIndex;

    @JsonProperty("scene_label")
    private String sceneLabel;

    @JsonProperty("description")
    private String description;

    @JsonProperty("layers")
    private List<LayerDirective> layers;

    @JsonProperty("composition")
    @Builder.Default
    private String composition = "fullscreen";

    @JsonProperty("timing")
    @Builder.Default
    private String timing = "auto";

    @JsonProperty("duration_hint_ms")
    private int durationHintMs;

    @JsonProperty("transition_in")
    private String transitionIn;

    @JsonProperty("transition_out")
    private String transitionOut;

    @JsonProperty("user_instruction")
    private String userInstruction;

    /**
     * A single layer in a scene.
     *
     * Each scene may have multiple layers:
     *   layer 0 = BACKGROUND (e.g. generated stock footage)
     *   layer 1 = PRIMARY (the main content, e.g. the user's clip)
     *   layer 2 = OVERLAY (an overlaid element, e.g. a gif, animation)
     *
     * Each layer has a source:
     *   PROVIDED — the user supplied the asset (referenced via assetIndex or a description match)
     *   GENERATE — the user wants the system to generate it (AI image/video)
     *   AUTO — the system decides
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class LayerDirective {

        @JsonProperty("layer_index")
        @Builder.Default
        private int layerIndex = 0;

        @JsonProperty("role")
        @Builder.Default
        private String role = "primary";

        @JsonProperty("source")
        @Builder.Default
        private String source = "auto";

        @JsonProperty("asset_index")
        @Builder.Default
        private int assetIndex = -1;

        @JsonProperty("asset_description")
        private String assetDescription;

        @JsonProperty("generation_prompt")
        private String generationPrompt;

        @JsonProperty("generation_type")
        private String generationType;

        @JsonProperty("effect")
        private String effect;

        @JsonProperty("opacity")
        @Builder.Default
        private double opacity = 1.0;

        public boolean isProvided() {
            return "provided".equals(source) && assetIndex >= 0;
        }

        public boolean isGenerate() {
            return "generate".equals(source) && generationPrompt != null;
        }
    }

    // ─── Helpers ───────────────────────────────────────────────

    public boolean hasMultipleLayers() {
        return layers != null && layers.size() > 1;
    }

    public LayerDirective getPrimaryLayer() {
        if (layers == null || layers.isEmpty()) return null;
        return layers.stream()
                .filter(l -> "primary".equals(l.getRole()))
                .findFirst()
                .orElse(layers.get(0));
    }

    public LayerDirective getBackgroundLayer() {
        if (layers == null) return null;
        return layers.stream()
                .filter(l -> "background".equals(l.getRole()))
                .findFirst()
                .orElse(null);
    }

    public boolean needsGeneration() {
        return layers != null && layers.stream().anyMatch(LayerDirective::isGenerate);
    }
}
