package com.BossAi.bossAi.service.director;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.util.List;

/**
 * Parsed user editing intent.
 *
 * Instead of treating the prompt as "text to generate a script from",
 * UserEditIntent breaks it down into structural editing decisions:
 *   - WHICH asset has which ROLE (intro, content, outro)
 *   - WHERE to place things on the timeline
 *   - WHAT pacing/style the user prefers
 *
 * Generated by UserIntentParser (GPT parses the prompt).
 * Fed into CutEngine, EdlGenerator, ScriptStep.
 *
 * If the user gave no editing hints,
 * the fields get sensible defaults (auto).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserEditIntent {

    /**
     * The overall goal of the video in 1 sentence.
     * E.g. "educational video about top 5 AI tools"
     */
    @JsonProperty("overall_goal")
    private String overallGoal;

    /**
     * List of assets with their assigned roles/positions.
     * Each element = 1 user asset + its role in the edit.
     */
    @Builder.Default
    @JsonProperty("placements")
    private List<AssetPlacement> placements = List.of();

    /**
     * Editing pace preference.
     * "fast", "moderate", "slow", "auto" (default auto — the system decides).
     */
    @Builder.Default
    @JsonProperty("pacing_preference")
    private String pacingPreference = "auto";

    /**
     * Structural hints extracted from the prompt.
     * E.g. ["intro first", "show product in middle", "end with CTA"]
     */
    @Builder.Default
    @JsonProperty("structure_hints")
    private List<String> structureHints = List.of();

    /**
     * Does the user explicitly control the asset order?
     * true = the user said "this one first, this one second..."
     * false = the user lets the system/GPT decide
     */
    @JsonProperty("user_controls_order")
    private boolean userControlsOrder;

    /**
     * Editing style extracted from the prompt (if provided).
     * E.g. "cinematic", "fast-paced", "chill", "professional"
     * Null if the user didn't provide one.
     */
    @JsonProperty("editing_style")
    private String editingStyle;

    /**
     * Preferred final video length (ms).
     * 0 = auto (the system decides based on the content).
     */
    @JsonProperty("target_duration_ms")
    private int targetDurationMs;

    /**
     * Parsing justification — why GPT interpreted the prompt this way.
     * For debugging, does not affect the logic.
     */
    @JsonProperty("reasoning")
    private String reasoning;

    /**
     * Detailed per-scene instructions — what exactly should appear in each scene.
     * Each SceneDirective describes layers (background/primary/overlay),
     * asset sources (provided/generate), composition, timing.
     *
     * If the user described scenes in the prompt (e.g. "first scene = intro with a stock market in the background"),
     * GPT parses that into SceneDirectives.
     * An empty list = the user didn't describe specific scenes → the system decides.
     */
    @Builder.Default
    @JsonProperty("scene_directives")
    private List<SceneDirective> sceneDirectives = List.of();

    // ─── Placement per asset ───────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class AssetPlacement {

        /** Index of the asset in the custom media list (0-based, = orderIndex) */
        @JsonProperty("asset_index")
        private int assetIndex;

        /**
         * Editing role of this asset.
         * Values: intro, hook, content, b-roll, product-shot,
         *           testimonial, transition, outro, cta, background, auto
         */
        @JsonProperty("role")
        private String role;

        /**
         * Where on the timeline to place this asset.
         * "beginning", "middle", "end", "at_topic_change",
         * "after_hook", "before_cta", "auto"
         */
        @JsonProperty("timing")
        private String timing;

        /**
         * Hint for how many ms this asset should last.
         * 0 = auto (the system/GPT decides).
         */
        @JsonProperty("duration_hint_ms")
        private int durationHintMs;

        /**
         * Description of the role from the user's prompt (quote or paraphrase).
         * E.g. "user said: 'this should be the intro'"
         */
        @JsonProperty("user_instruction")
        private String userInstruction;

        /**
         * Description of the scene assigned to this asset — what the user wants to see.
         * E.g. "Morocco at sunset, slow zoom, moody"
         */
        @JsonProperty("scene_description")
        private String sceneDescription;

        /**
         * Scene mood (calm, energetic, dramatic, mysterious, etc.)
         */
        @JsonProperty("mood")
        private String mood;
    }

    // ─── Helper methods ────────────────────────────────────────

    /**
     * Did the user provide ANY editing hints?
     * If not — the system runs in auto mode (as before).
     */
    public boolean hasExplicitInstructions() {
        if (sceneDirectives != null && !sceneDirectives.isEmpty()) {
            return true;
        }
        if (placements != null && !placements.isEmpty()) {
            return placements.stream().anyMatch(p ->
                    p.getRole() != null && !"auto".equals(p.getRole()));
        }
        return structureHints != null && !structureHints.isEmpty();
    }

    /**
     * Find the placement for a given asset index.
     */
    public AssetPlacement getPlacementForAsset(int assetIndex) {
        if (placements == null) return null;
        return placements.stream()
                .filter(p -> p.getAssetIndex() == assetIndex)
                .findFirst()
                .orElse(null);
    }

    /**
     * Find assets with a given role.
     */
    public List<AssetPlacement> getPlacementsByRole(String role) {
        if (placements == null) return List.of();
        return placements.stream()
                .filter(p -> role.equals(p.getRole()))
                .toList();
    }

    /**
     * Did the user describe specific scenes with layers?
     */
    public boolean hasSceneDirectives() {
        return sceneDirectives != null && !sceneDirectives.isEmpty();
    }

    /**
     * Find the SceneDirective for a given scene index.
     */
    public SceneDirective getSceneDirective(int sceneIndex) {
        if (sceneDirectives == null) return null;
        return sceneDirectives.stream()
                .filter(sd -> sd.getSceneIndex() == sceneIndex)
                .findFirst()
                .orElse(null);
    }

    /**
     * Does any scene require asset generation?
     */
    public boolean needsAssetGeneration() {
        return sceneDirectives != null && sceneDirectives.stream()
                .anyMatch(SceneDirective::needsGeneration);
    }
}
