package com.BossAi.bossAi.service.generation.context;

import lombok.Builder;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Assets generated for a single TikTok Ad scene.
 *
 * Filled in sequentially by:
 *   - ImageStep  → imageUrl
 *   - VideoStep  → videoUrl, videoLocalPath
 *   - LayerAssetGenerator → layerAssetIds (for multi-layer scenes)
 *
 * Przechowywany w GenerationContext.scenes[].
 */
@Data
@Builder
public class SceneAsset {

    /**
     * Scene index — corresponds to ScriptResult.SceneScript.index.
     */
    private int index;

    /**
     * Image prompt from ScriptResult (a copy — for convenience in logs and retries).
     */
    private String imagePrompt;

    /**
     * Prompt ruchu z ScriptResult.
     */
    private String motionPrompt;

    /**
     * Scene duration in ms — used by RenderStep for the timeline.
     */
    private int durationMs;

    /**
     * URL of the generated image (fal.ai CDN or LocalStorage URL).
     * Set by ImageStep.
     */
    private String imageUrl;

    /**
     * URL of the generated video clip (fal.ai CDN).
     * Set by VideoStep before downloading the file.
     */
    private String videoUrl;

    /**
     * Local path of the video file after downloading from the fal.ai CDN.
     * Set by VideoStep after it's saved by StorageService.
     * RenderStep uses this path for the FFmpeg concat.
     */
    private String videoLocalPath;

    /**
     * Narration fragment for this scene — goes into the SRT.
     */
    private String subtitleText;

    /**
     * Map of layerIndex → ProjectAsset UUID for the additional layers.
     * Layer 0 = the main asset (imageUrl/videoUrl above).
     * Layer 1+ = generated by LayerAssetGenerator.
     *
     * Used by EdlGeneratorService to emit multi-layer segments.
     */
    @Builder.Default
    private Map<Integer, UUID> layerAssetIds = new HashMap<>();
}