spring.application.name=bossAi

spring.datasource.url=jdbc:postgresql://localhost:5432/boss
spring.datasource.username=boss
spring.datasource.password=boss

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=F7p2BLlnl8SFzxSwK1zAbVNlhArKCb7v
jwt.expiration=86400000

allowed.origin=http://localhost:5173/

replicate.api-key=r8_QsmSO8M4GXaglfuUSKFw9ZIV87cUbuF0O6nLv
replicate.base-url=https://api.replicate.com/v1

cloudflare.account-id=7f1967ab07d42cf6cb8c00e88f9efab3
cloudflare.api-token=9WAtd0tasm-H7gcVWFc1ZoZDbMupZPktVZ-Pwodf
cloudflare.base-url=https://api.cloudflare.com/client/v4

storage.images.path=uploads/images
storage.images.public-url=/images

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zydek1230@gmail.com
spring.mail.password=drlm uqvp zyml ydio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

server.forward-headers-strategy=framework