package com.BossAi.bossAi.service.dna;

import com.BossAi.bossAi.dto.edl.EdlColorGrade;
import com.BossAi.bossAi.dto.edl.EdlEffect;
import com.BossAi.bossAi.dto.edl.EdlSubtitleConfig;
import com.BossAi.bossAi.dto.edl.EdlTextOverlay;
import com.BossAi.bossAi.dto.edl.EdlTransition;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Schema for a DNA preset config file (resources/dna-presets/<id>.json).
 * All values loaded at runtime — no preset logic hardcoded in Java.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class DnaPresetConfig {

    @JsonProperty("id")
    private String id;

    @JsonProperty("display_name")
    private String displayName;

    @JsonProperty("pacing")
    private String pacing;

    /** Global color grade — applied to all segments unless overridden per beat. */
    @JsonProperty("color_grade")
    private EdlColorGrade colorGrade;

    /**
     * Per-beat configuration. Keys are beat letters: A, B, C, D, E.
     * Each beat has timing, available scene patterns, and a default color grade.
     */
    @JsonProperty("beats")
    private Map<String, BeatConfig> beats;

    @JsonProperty("subtitle_config")
    private EdlSubtitleConfig subtitleConfig;

    @JsonProperty("audio_config")
    private AudioConfig audioConfig;

    /**
     * Text overlay templates for this preset.
     * Placeholders like {HOOK_TEXT} are filled by GPT at generation time.
     */
    @JsonProperty("text_overlay_templates")
    private List<TextOverlayTemplate> textOverlayTemplates;

    // ─── Nested types ─────────────────────────────────────────────────────────

    /**
     * Configuration for a single beat (A–E).
     * scenePatterns is a rotating list — first scene in beat uses pattern[0],
     * second uses pattern[1], etc. (wraps around if more scenes than patterns).
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class BeatConfig {

        @JsonProperty("name")
        private String name;

        /** Absolute start time for 30s standard video (ms). Scaled for 15s/45s. */
        @JsonProperty("start_ms")
        private int startMs;

        @JsonProperty("end_ms")
        private int endMs;

        @JsonProperty("min_duration_ms")
        private int minDurationMs;

        @JsonProperty("max_duration_ms")
        private int maxDurationMs;

        @JsonProperty("scene_patterns")
        private List<ScenePattern> scenePatterns;

        /** Default color grade override for all scenes in this beat. */
        @JsonProperty("color_grade_override")
        private EdlColorGrade colorGradeOverride;
    }

    /**
     * One scene pattern within a beat — effect + transition + optional
     * color grade that overrides the beat-level default.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ScenePattern {

        @JsonProperty("effect")
        private EdlEffect effect;

        @JsonProperty("transition")
        private EdlTransition transition;

        @JsonProperty("color_grade_override")
        private EdlColorGrade colorGradeOverride;
    }

    /** Audio configuration for the preset (volumes per beat, music style). */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class AudioConfig {

        @JsonProperty("voiceover_volume")
        private double voiceoverVolume;

        @JsonProperty("voiceover_fade_out_ms")
        private int voiceoverFadeOutMs;

        /** Music volume per beat — key is beat letter (A–E). */
        @JsonProperty("volume_by_beat")
        private Map<String, Double> volumeByBeat;

        @JsonProperty("music_fade_in_ms")
        private int musicFadeInMs;

        @JsonProperty("music_fade_out_ms")
        private int musicFadeOutMs;

        @JsonProperty("music_style")
        private String musicStyle;
    }

    /**
     * Template for a text overlay generated by GPT.
     * The `placeholder` field matches a GPT output variable (e.g. {HOOK_TEXT}).
     * start_ms / end_ms are beat-relative defaults for 30s standard video.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class TextOverlayTemplate {

        @JsonProperty("beat")
        private String beat;

        @JsonProperty("placeholder")
        private String placeholder;

        @JsonProperty("type")
        private String type;

        @JsonProperty("start_ms")
        private int startMs;

        @JsonProperty("end_ms")
        private int endMs;

        @JsonProperty("layer")
        private int layer;

        @JsonProperty("style")
        private EdlTextOverlay.TextStyle style;

        /** Simplified position string ("center", "bottom_third", "bottom_quarter"). */
        @JsonProperty("position")
        private String position;

        @JsonProperty("animation")
        private String animation;

        @JsonProperty("animation_duration_ms")
        private int animationDurationMs;
    }
}
