package com.BossAi.bossAi.service.edl;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.util.List;

/**
 * Edit DNA — the unique editing "personality" generated by the LLM Director.
 *
 * Generated ONCE per project, BEFORE generating the EDL.
 * Determines how GPT will generate the EDL — which effects, cut rhythm, color.
 * The same seed = the same edit_dna = the same film (reproducibility).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class EditDna {

    /**
     * Seed for reproducibility. The same seed + the same data = the same output.
     */
    private long seed;

    /**
     * Editing personality — describes the overall character of the edit.
     * Np. "chaotic_precise", "smooth_flowing", "aggressive_minimal", "cinematic_slow_burn"
     */
    @JsonProperty("edit_personality")
    private String editPersonality;

    /**
     * Cut rhythm — how to organize the cuts over time.
     */
    @JsonProperty("cut_rhythm")
    private CutRhythm cutRhythm;

    /**
     * Effect palette — which effects dominate, which are forbidden.
     */
    @JsonProperty("effect_palette")
    private EffectPalette effectPalette;

    /**
     * Color grading — wizualny charakter projektu.
     */
    @JsonProperty("color_grade")
    private ColorGrade colorGrade;

    /**
     * Strategia hook (pierwsze 2-3 sekundy).
     */
    @JsonProperty("hook_strategy")
    private String hookStrategy;

    /**
     * Editing intent — defines the CHARACTER of the cuts.
     * Generated based on the narration + music + mood analysis.
     *
     * It is not random — GPT analyzes the content and picks a specific strategy.
     * Each generation has a different intent = each film looks different.
     */
    @JsonProperty("editing_intent")
    private EditingIntent editingIntent;

    /**
     * A short justification of the LLM's decision (for logs/debugging).
     */
    @JsonProperty("reasoning")
    private String reasoning;

    // ─── Nested DTOs ────────────────────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class CutRhythm {

        /**
         * Cut mode:
         * - sparse_with_bursts: long shots (2-4 beats), then a burst of quick ones on the drop
         * - on_beat_strict: cut exactly on the beat, little humanize
         * - off_beat_syncopated: cuts between beats, unexpected
         * - breathing: cuts on pauses in the music, not on the beat
         * - escalating: progressively faster cuts toward the drop
         */
        private String mode;

        /**
         * What triggers a burst of quick cuts (e.g. "drop", "peak", "chorus").
         */
        @JsonProperty("burst_trigger")
        private String burstTrigger;

        /**
         * Humanize in ms — a random cut offset so they don't sound mechanical.
         */
        @JsonProperty("humanize_ms")
        private int humanizeMs;

        /**
         * Minimum shot duration in ms (nothing shorter than this).
         */
        @JsonProperty("min_cut_ms")
        private int minCutMs;

        /**
         * Maximum shot duration in ms (nothing longer than this).
         */
        @JsonProperty("max_cut_ms")
        private int maxCutMs;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EffectPalette {

        /**
         * The project's main effect (used most often).
         */
        private String primary;

        /**
         * The secondary effect (complements the primary).
         */
        private String secondary;

        /**
         * Efekt specjalny na drop/peak (sygnatura projektu).
         */
        @JsonProperty("drop_signature")
        private String dropSignature;

        /**
         * Effects FORBIDDEN in this project (so every film is different).
         */
        private List<String> forbidden;

        /**
         * Preferred base intensity (0.0-1.0).
         */
        @JsonProperty("base_intensity")
        private double baseIntensity;
    }

    /**
     * Intent-Based Editing — GPT-driven editing philosophy.
     *
     * Instead of random cuts, GPT analyzes the content + music and picks:
     *   - intent: the editing philosophy (build_tension, contrast_shock, ...)
     *   - pattern: the distribution of cuts over time (slow_to_fast, wave, ...)
     *   - arc: the film's phases with cut density and mood
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EditingIntent {

        /**
         * Main editing intent:
         *   build_tension | rhythmic_pulse | contrast_shock | flowing_narrative |
         *   staccato_energy | emotional_wave | reveal_punctuate
         */
        private String intent;

        /**
         * Cut tempo pattern:
         *   slow_to_fast | fast_to_slow | wave | constant_high |
         *   on_beat_consistent | long_hold_then_burst | breathing_with_pauses
         */
        private String pattern;

        /**
         * Editing arc — how the cut density changes over time.
         */
        private List<EditingArc> arc;

        /**
         * Uzasadnienie wyboru tego intentu/patternu.
         */
        private String reasoning;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EditingArc {
        /** Phase: opening, buildup, middle, climax, resolution, outro */
        private String phase;
        /** Cut density: very_low, low, medium, high, very_high */
        private String density;
        /** Mood: curious, building, intense, euphoric, reflective, urgent */
        private String mood;
        /** Percentage of the film at which the phase begins (0.0-1.0) */
        @JsonProperty("start_pct")
        private double startPct;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ColorGrade {

        /**
         * Preset koloru:
         * cold_matte, warm_golden, high_contrast, desaturated, vibrant_pop, moody_dark, clean_bright
         */
        private String preset;

        @JsonProperty("contrast_boost")
        private double contrastBoost;

        private double saturation;

        private double brightness;

        private double vignette;
    }
}
