package com.BossAi.bossAi.service.director.composition;

import lombok.*;

/**
 * Propozycja wielowarstwowej kompozycji dla jednej sceny.
 *
 * Generated by AutonomousCompositionDecider based on rules (e.g. TalkingHeadBg,
 * CtaOverlay, ProductReveal) and sent to GPT for verification.
 *
 * GPT decyduje: accept=true → stosujemy SceneDirective, accept=false → fullscreen fallback.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CompositionCandidate {

    /** Indeks sceny (= indeks w JustifiedCuts) */
    private int sceneIndex;

    /** Name of the rule that generated the candidate */
    private String rule;

    /**
     * Typ kompozycji:
     *   pip       — picture-in-picture: primary (mniejszy) na tle background
     *   overlay   — primary fullscreen + overlay na wierzchu (logo, CTA, product)
     *   fullscreen — a single layer (default — the candidate is not accepted)
     */
    @Builder.Default
    private String composition = "fullscreen";

    /** Index of the asset (from AssetProfile.index) playing the primary role */
    @Builder.Default
    private int primaryAssetIndex = -1;

    /** Index of the asset playing the background role (-1 = none) */
    @Builder.Default
    private int backgroundAssetIndex = -1;

    /** Index of the asset playing the overlay role (-1 = none) */
    @Builder.Default
    private int overlayAssetIndex = -1;

    /** Opis wizualny primary assetu (dla GPT kontekstu) */
    private String primaryDescription;

    /** Opis wizualny background assetu */
    private String backgroundDescription;

    /** Opis wizualny overlay assetu */
    private String overlayDescription;

    /** Fragment narracji w tym momencie */
    private String narrationText;

    /** Typ segmentu narracji (hook/setup/point/emphasis/climax/cta) */
    private String narrationType;

    /** DNA phase (A=hook, B=problem, C=tension, D=reveal, E=transform, F=cta) */
    private String dnaBeat;

    /** Justification for the rule — why this composition makes sense */
    private String reasoning;
}
